base_url = "https://fdtv.me"
title = "fdtv.me"
compile_sass = true
build_search_index = true
generate_feed = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]

highlight_code = true
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_theme = "material-light"

[extra]

author = "Aleksey"
display_author = true
favicon = "/img/favicon.png"

default_theme = "light"
list_pages = false

header_nav = [
    { url = "/", name = "/home/" },
    { url = "/posts", name = "/posts/" },
]
